## Numpy
수치해석용 파이썬 패키지
* 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원 
* 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용됨
* 행렬과 같은 다차원 배열의 경우 효율적

### numpy array 특징
* 모든 원소가 같은 자료형이어야 한다.
* 원소의 갯수를 바꿀 수 없다.


## numpy array vs python list
* 여러 값을 보관한다는 공통점

### 차이점?
파이썬은 자체적으로 배열 자료형을 제공하지 않는다.
* 문법 차이
* 성능 차이 - 값이 저장되는 방식의 차이로 인해 발생
    * python list : 다양한 자료형들을 동시에 입력 가능
    * numpy array : 같은 자료형의 값만 입력 가능

### numpy array

In [1]:
import numpy as np
from timeit import timeit

In [7]:
nar = np.array([0,1,2,3,4,5,6,7,8,9])

In [8]:
nar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(nar)

numpy.ndarray

In [10]:
nar * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### python list

In [11]:
plist = [0,1,2,3,4,5,6,7,8,9]

* 일반적인 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼으로 증가한다.

In [12]:
plist * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
mul_plist = [ num*2 for num in plist ]

In [15]:
mul_plist

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [16]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [17]:
2 * a + b

array([12, 24, 36])

In [18]:
a == 2

array([False,  True, False])

In [19]:
b > 10

array([False,  True,  True])

In [20]:
(a == 2) & (b > 10)

array([False,  True, False])

---

### 속도 비교

In [3]:
x = np.arange(100000000)
y = list(range(100000000))

In [4]:
timeit(lambda: x * 2, number = 1)

3.4208294000000024

In [5]:
timeit(lambda: [n * 2 for n in y], number = 1)

29.956887800000004