In [1]:
import numpy as np

In [2]:
N = np.random.rand(3, 5)

In [3]:
N

array([[0.28950849, 0.75249425, 0.31607489, 0.4428642 , 0.04160828],
       [0.636311  , 0.21744617, 0.23527433, 0.21299984, 0.21615225],
       [0.07010087, 0.04666851, 0.50374259, 0.60187623, 0.26737954]])

In [5]:
Z = np.zeros((2,4)) # zeros는 괄호를 꼭 두번 입력해야한다.

In [6]:
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
N[0][2] # 1행 3열

0.3160748942964464

In [12]:
A = np.array([[0,1,2,-1,],
             [1,2,1,2],
             [-1,3,0,4]])

In [14]:
A.T

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2,  4]])

In [15]:
AA = np.array([[0,1,-1],
             [1,2,3],
             [2,1,0],
             [-1,2,4]])

In [16]:
AA

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2,  4]])

In [17]:
B = np.array([[0,2],
             [1,1],
             [-1,2]])

In [22]:
B[0][1]

2

In [27]:
AA[1][1]

2

In [26]:
AA[3][0]

-1

In [29]:
print(AA)
print(AA[1][1])
print(AA[3][0])

[[ 0  1 -1]
 [ 1  2  3]
 [ 2  1  0]
 [-1  2  4]]
2
-1


---

### 요소별 곱하기

In [38]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])

In [39]:
A * B

array([[ 0,  2,  6],
       [ 8,  0,  6],
       [ 7, 16,  0]])

### 내적곱

In [40]:
np.dot(A,B)

array([[ 7,  7,  4],
       [16, 16, 13],
       [25, 25, 22]])

In [41]:
A @ B

array([[ 7,  7,  4],
       [16, 16, 13],
       [25, 25, 22]])

---

* 숫자/행렬 스칼라 곱 :  *
* 행렬 덧셈 : +
* 행렬 곱셈 : @

In [42]:
A @ B + (A + 2 * B)

array([[ 8, 11, 11],
       [24, 21, 21],
       [34, 37, 31]])

In [43]:
# A
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])
# B
B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])
# C
C = np.array([
    [2, -1],
    [-3, 3]
])
# D
D = np.array([
    [-5, 1],
    [2, 0]
])

In [45]:
result = 2*A @ (-1*B) @ (3*C + D)
result

array([[  34,  -28],
       [ 110, -130]])

---

In [33]:
array_A = np.arange(10)
array_A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
array_B = np.arange(10, 20)
array_B

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
array_A * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
array_A / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

* array * 2 
* array + 2 
* array / 2
* array ** 2 

In [37]:
array_A + array_B

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 전치 행렬
####  transpose
* 행과 열을 바꿈

In [68]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [69]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 단위 행렬
#### identity matrix
* 단위 행렬은 항상 정사각형의 모양
* 어떤 행렬이든 간에 단위 행렬을 곱하면 기존 행렬이 그대로 유지

In [71]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
I = np.array([
    [1, 0],
    [0, 1]
])

In [50]:
D = np.array([
    [-5, 1],
    [2, 0]
])

In [51]:
D @ I

array([[-5,  1],
       [ 2,  0]])

### 역행렬
#### inverse matrix
* A에 곱했을 때 단위 행렬 I가 나오도록 하는 행렬
* 역행렬은 꼭 정사각형이어야 한다
* 모든 행렬에 역행렬이 있는 건 아님

In [60]:
A = np.array([
    [3, 4],
    [1, 2]
])

#### 선형대수(Linear Algebra) 함수

In [63]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [66]:
np.linalg.inv(A)

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [64]:
A_inverse @ A

array([[1., 0.],
       [0., 1.]])

---

In [73]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

In [74]:
result = B.T @ (2 * A.T) @ (3 * np.linalg.pinv(C) + D.T)
result

array([[20., 98.],
       [56., 60.]])